### ISSUE TITLE
update readme syntax

### ISSUE THREAD

**Issue by spawes** [jperon/gabctk#5]
in `readme.md` you have
```
   gabctk.py -i </chemin/vers/le/fichier/source.gabc> \
             [-o </chemin/vers/le/fichier/destination.mid>] \
             [-l </chemin/vers/le/fichier/destination.ly>] \
             [-c </chemin/vers/le/fichier/destination.abc>] \
             [-x </chemin/vers/le/fichier/destination.xml>] \
             [-b </chemin/vers/le/fichier/destination.tab>] \
             [-e </chemin/vers/le/fichier/destination.txt>] \
             [-m </chemin/vers/le/fichier/destination.mus>] \
             [-t tempo] \
             [-d transposition] \
             [-a alerte] \
```
but in `gabctk.py --help` is much more. That is OK. But arguments like `-h -n -v` are completely missing. I predict that information in output of `-h`  is true, so please update readme.md.

Anyway, gabctk is great  and I thank you so much. I am fighting with scores and thanks to you I can finally learn gregorian chant by myself.

**Comment by jperon** [comment]
Thank you for the report, and for the comment!

**Comment by jperon** [comment]
By the way, I [translated the documentation](https://github.com/jperon/gabctk/blob/master/README-en.md) (thanks to [DeepL](https://www.deepl.com)).
